OPENAI_API_KEY = ("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")
PINECONE_API_KEY = ("8c2079b0-03bf-40e3-aacd-d41e5bd4c589")
openai.api_key = "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"
